  DROP TABLE IF EXISTS Program;
DROP TABLE IF EXISTS ActivityCategory;
DROP TABLE IF EXISTS Activity;
DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS Title;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS ActivityReport;
DROP TABLE IF EXISTS WorksAt;

CREATE TABLE Program(
  name VARCHAR(255) DEFAULT '',
  PRIMARY KEY (name)
);

CREATE TABLE ActivityCategory(
  name VARCHAR(255) DEFAULT '',
  program VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (program) REFERENCES Program(name) ON DELETE RESTRICT,
  PRIMARY KEY (name)
);

CREATE TABLE Activity(
  name VARCHAR(255) DEFAULT '',
  category VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (category) REFERENCES ActivityCategory(name) ON DELETE RESTRICT,
  PRIMARY KEY (name)
);

CREATE TABLE Area(
  name VARCHAR(255) DEFAULT '',
  PRIMARY KEY (name)
);

CREATE TABLE School(
  name VARCHAR(255) DEFAULT '',
  area VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (area) REFERENCES Area(name) ON DELETE RESTRICT,
  PRIMARY KEY (name)
);

CREATE TABLE Title(
  name VARCHAR(255) DEFAULT '',
  PRIMARY KEY (name)
);

CREATE TABLE Staff(
  name VARCHAR(255) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  phone VARCHAR(255) DEFAULT '',
  title VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (title) REFERENCES Title(name) ON DELETE RESTRICT,
  PRIMARY KEY (name)
);

CREATE TABLE Grade(
  name VARCHAR(255),
  listOrder INT NOT NUll,
  PRIMARY KEY(name)
);

CREATE TABLE ActivityReport(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  date DATETIME NOT NULL,
  comment VARCHAR(255) DEFAULT '',
  nrOfParticipants INT UNSIGNED DEFAULT NULL,
  activity VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (activity) REFERENCES Activity(name) ON DELETE RESTRICT,
  staff VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (staff) REFERENCES Staff(name) ON DELETE RESTRICT,
  school VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (school) REFERENCES School(name) ON DELETE RESTRICT,
  grade VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (grade) REFERENCES Grade(name) ON DELETE RESTRICT,
  PRIMARY KEY (id),
  CONSTRAINT invalid_nrOfParticipants CHECK (nrOfParticipants >= 0)
);

CREATE TABLE WorksAt(
  staff VARCHAR(255),
  FOREIGN KEY (staff) REFERENCES Staff(name) ON DELETE RESTRICT,
  area VARCHAR(255),
  FOREIGN KEY (area) REFERENCES Area(name) ON DELETE RESTRICT,
  PRIMARY KEY(staff,area)
);